stages:
  annotator_performance:
    cmd: poetry run papermill code/01-annotator_performance.ipynb code/01-annotator_performance.ipynb
    deps:
      - code/01-annotator_performance.ipynb
      - data/labeled_data/full.csv.zip
    outs:
      - results/tables/coder_agreement.tex
  create_popbert_model:
    cmd: poetry run papermill code/02-create_popbert_model.ipynb code/02-create_popbert_model.ipynb
    deps:
      - code/02-create_popbert_model.ipynb
      - src/bert/training.py
      - src/bert/utils.py
      - src/bert/dataset/dataset.py
      - src/bert/dataset/strategies.py
      - data/labeled_data/train.csv.zip
      - data/labeled_data/test.csv.zip
    outs:
      - results/popbert_model/
  model_performance:
    cmd: poetry run papermill code/03-model_performance.ipynb code/03-model_performance.ipynb
    deps:
      - code/03-model_performance.ipynb
      - data/labeled_data/test.csv.zip
    outs:
      - results/tables/model_performance.tex
  make_predictions:
    cmd: poetry run papermill code/04-make_predictions.ipynb code/04-make_predictions.ipynb
    deps:
      - code/04-make_predictions.ipynb
      - data/raw/sentences.parquet.gzip
    outs:
      - data/interim/sentence_predictions.parquet.gzip
  all_dimensions:
    cmd: poetry run papermill code/05-all_dimensions.ipynb code/05-all_dimensions.ipynb
    deps:
      - code/05-all_dimensions.ipynb
      - data/raw/sentences.parquet.gzip
      - data/interim/sentence_predictions.parquet.gzip
    outs:
      - results/figures/all_dimensions_normalized.pdf
      - results/figures/all_dimensions_orig.pdf
  run_gruendl:
    cmd: Rscript code/08-run_gruendl.R
    deps:
      - code/08-run_gruendl.R
      - data/raw/sentences.parquet.gzip
    outs:
      - data/interim/gruendl.parquet.gzip
  selected_examples:
    cmd: poetry run papermill code/09-selected_examples_table.ipynb code/09-selected_examples_table.ipynb
    deps:
      - code/09-selected_examples_table.ipynb
      - data/raw/sentences.parquet.gzip
      - data/interim/sentence_predictions.parquet.gzip
      - data/interim/gruendl.parquet.gzip
    outs:
      - results/tables/selected_examples.tex
  populism_by_politician:
    cmd: poetry run papermill code/06-populism_by_politician.ipynb code/06-populism_by_politician.ipynb
    deps:
      - code/06-populism_by_politician.ipynb
      - src/pop_aggregate.py
      - data/raw/sentences.parquet.gzip
      - data/interim/sentence_predictions.parquet.gzip
    outs:
      - results/tables/populist_politicians.tex
  populism_by_speech:
    cmd: poetry run papermill code/07-populism_by_speech.ipynb code/07-populism_by_speech.ipynb
    deps:
      - code/07-populism_by_speech.ipynb
      - data/raw/sentences.parquet.gzip
      - data/interim/sentence_predictions.parquet.gzip
    outs:
      - results/figures/populism_by_party_measures_normalized.pdf
      - results/figures/populism_by_party_measures_orig.pdf
